### PR TITLE
CWL & Emoji update, change README, add @everyone tag on missing attacks.

### PR DESCRIPTION
**Pull request by curtiola**
Added emoji images for Ice Golem, Stone Slammer, Bat Spell, BH9 & Hog Glider.
Added additional emoji information to README.md
Left their ID #s blank in index.js since I am not hosting the bot publicly.
Added '@everyone' before the missing attacks embed, as suggested in issue #3.

### CODE REVIEW

**Comment by spAnser** [comment]
I think you changed the TH emoji IDs in this one?

I will most likely merge this weekend though, just been pretty busy.

**Comment by curtiola** [comment]
I did change them by mistake at first, then yesterday I changed the ID #s back to the original ones you used. (Still leaving the new emoji ID #s blank)
Since first opening the PR I also added the changes from the [Jonathan-Law fork](https://github.com/Jonathan-Law/discord-coc-war-announcer) that updated stuff for CWL.
He overhauled index.js, clans.js & added separate parseCurrentWar.js & parseCurrentLeague.js

**Comment by spAnser** [comment]
Sounds good then.

**Comment by curtiola** [comment]
!unannounce was broken in the Jonathan-Law index.js changes, fixed now.

Everything else seems fine.

**Comment by curtiola** [comment]
For CWL wars, it thinks everyone has 2 attacks, so that's not great. Not sure what to do about it right now, looking into it.

**Comment by spAnser** [comment]
No problem.

**Comment by curtiola** [comment]
Will reopen when I've tested this more.

**Comment by curtiola** [comment]
Lil status update;
CWL can designate our clan as the opponent, causing showmissing to announce the enemy missing attacks & using the wrong clan tag for a lot of the things.
Unsure exactly what to do right now, need to add a clan tag match check or something, slowly workin on it, but I am the big dumb lol.. I'll get 'er figured eventually but if you have any tips hit me with them please.

**Comment by spAnser** [comment]
Feel free to re open the pull request and I can merge it and look through stuff maybe figure it out. It is only on the develop branch anyways.

**Comment by spAnser** [comment]
I actually have some code in my local version for claiming accounts with the API token I need to merge in anyways. I'm not sure if they ever made that endpoint public yet so I was waiting for that before pushing.

**Comment by curtiola** [comment]
Oh ok cool, I'll check that out when/if you merge it.
Also, unsure if storing the CWL true/false string in `./node-persist/clan-storage` was the best way to do it, but that's what I did.

**Pull request merged**
